DROP DATABASE IF EXISTS cinema_app;

CREATE DATABASE cinema_app;

USE cinema_app;

CREATE TABLE details (
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	director VARCHAR(64) DEFAULT NULL,
	actors VARCHAR(256) DEFAULT NULL,
	synopsis TEXT,
	trailer VARCHAR(256) DEFAULT NULL COMMENT 'Youtube trailer URL'
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE movies (
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_detail INT(8) DEFAULT NULL,
	title VARCHAR(64) NOT NULL,
	duration INT(4) NOT NULL,
	classification ENUM('A', 'B', 'C') NOT NULL DEFAULT 'A',
	genre VARCHAR(64) NOT NULL,
	premiere_date DATE NOT NULL,
	image VARCHAR(128) NOT NULL DEFAULT 'cinema.png',
	status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
	FOREIGN KEY (id_detail) REFERENCES details(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE timetables (
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	id_movie INT(8) NOT NULL,
	date DATE NOT NULL,
	time TIME NOT NULL,
	room VARCHAR(64) NOT NULL DEFAULT 'Room 1',
	price DOUBLE NOT NULL DEFAULT 0,
	FOREIGN KEY (id_movie) REFERENCES movies(id)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE banners (
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(64) NOT NULL,
	date DATE NOT NULL,
	image VARCHAR(128) NOT NULL,
	status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE'
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE news (
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(64) NOT NULL,
	publication_date DATE NOT NULL,
	status ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
	details TEXT NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE users (
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL UNIQUE KEY,
	name VARCHAR(64) NOT NULL,
	email VARCHAR(64) NOT NULL,
	password VARCHAR(256) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

CREATE TABLE user_profiles (
	id INT(8) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(32) NOT NULL,
	profile VARCHAR(256) NOT NULL,
	FOREIGN KEY (username) REFERENCES users(username)
) ENGINE = InnoDB DEFAULT CHARSET = utf8;

DESCRIBE details;

DESCRIBE movies;

DESCRIBE timetables;

DESCRIBE banners;

DESCRIBE news;

DESCRIBE users;

DESCRIBE user_profiles;
